spring:
  application:
    name: interview
server: 
  port: 22222 
  context-path: /
logging:
  file: ./interview.log #输出到本项目，上线后只能输出到一个地方，磁盘和文件，待认证
  level: 
    org.springframework.web: INFO
  path: /logs/${spring.application.name} #输出到磁盘目录
httpclient: 
  config:
#    proxyhost: 127.0.0.1 # 代理的host 
#    proxyPort: 2223 # 代理端口 
    retryTime: 3 # 连接超时或异常重试次数
    keepAliveTime: 30 # 长连接保持时间，单位为s
    connMaxTotal: 200 # 连接池最大连接数  
    maxPerRoute: 100 # 每个路由最大连接数
    connectTimeout: 10000 # 连接超时时间，单位ms
    connectRequestTimeout: 2000 # 请求超时时间  
    socketTimeout: 60000 # sock超时时间  
    timeToLive: 60 # 连接存活时间，单位s
    
threadPool: 
  corePoolSize: 2
  maximumPoolSize: 9
  keepAliveTime: 60L
  queueCapacity: 16
