spring:
  application:
    name: interview
server: 
  port: 22222 
  context-path: /
logging:
  file: ./interview.log #输出到本项目
  level: 
    org.springframework.web: INFO
  path: /logs/${spring.application.name} #输出到磁盘目录